### ISSUE TITLE
_max_results issue

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#103]
When _max_results is used with other parameters using '&', the WAPI call does not return and it gets timed out.

To simulate this from CURL, the following has the same effect.

curl -H "Content-Type: application/json" -k1 -u cloud:cloud -X GET https://10.39.12.170/wapi/v2.3/networkview?_return_fields=name,is_default,extattrs&_max_results=-10

This is because '&' is used as background process in command line.

In order to fix this issue, double-quotes around URL is needed. So this works.

curl -H "Content-Type: application/json" -k1 -u cloud:cloud -X GET "https://10.39.12.170/wapi/v2.3/networkview?_return_fields=name,is_default,extattrs&_max_results=-10"

Surprisingly, connector.py has the same issue.

Putting double-quote around the URL resolves in CURL but not sure in connector case since we are passing URL string to a library API. (Double-quotes are better than single-quotes.)

Event putting \ in front of & works with CURL.

curl -H "Content-Type: application/json" -k1 -u cloud:cloud -X GET https://10.39.12.170/wapi/v2.3/networkview?_return_fields=name,is_default,extattrs\&_max_results=-10

**Comment by bondar-pavel** [comment]
infoblox-client uses requests python library, so these shell escaping issues should not apply to it. I made some debugging in python console to reproduce this issue exists. My test results shows that this issue doesn't apply to infoblox-client.

Here is the output from my console with maximum debug.
Only one network exists on this Grid, so testing with 'max_results=-2':

> \> objects.Network.search_all(conn, max_results=-2)  
INFO:infoblox_client.connector:Sending get request to https://10.40.240.113/wapi/v1.4/network?_max_results=-2&_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs with parameters {'headers': {'Content-type': 'application/json'}, 'timeout': 10}
/usr/lib/python3.5/site-packages/requests-2.9.1-py3.5.egg/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
DEBUG:requests.packages.urllib3.connectionpool:"GET /wapi/v1.4/network?_max_results=-2&_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs HTTP/1.1" 200 None
[NetworkV4: _ref="network/ZG5zLm5ldHdvcmskMTAuNDAuMjQwLjAvMjQvMA:10.40.240.0/24/test", members="[AnyMember: name="stan_member.ft-ac.com", _struct="dhcpmember", ipv4addr="10.40.240.113"]", network="10.40.240.0/24", options="[DhcpOption: use_option="False", num="51", name="dhcp-lease-time", vendor_class="DHCP", value="43200", DhcpOption: use_option="True", num="6", name="domain-name-servers", vendor_class="DHCP", value="10.0.2.35", DhcpOption: use_option="True", num="3", name="routers", vendor_class="DHCP", value="10.40.240.1"]", network_view="test", NetworkV4: _ref="network/ZG5zLm5ldHdvcmskMTAuNDAuMTYuMC8yNC8w:10.40.16.0/24/test", members="[AnyMember: name="stan_member.ft-ac.com", _struct="dhcpmember", ipv4addr="10.40.240.113"]", network="10.40.16.0/24", options="[DhcpOption: use_option="False", num="51", name="dhcp-lease-time", vendor_class="DHCP", value="43200", DhcpOption: use_option="True", num="6", name="domain-name-servers", vendor_class="DHCP", value="10.0.2.35", DhcpOption: use_option="True", num="3", name="routers", vendor_class="DHCP", value="10.40.16.1"]", network_view="test"]

Network is found and shown in output.
In the second case max_results is set to -1 and expected results is raising an exception,
which is observed:

> \> objects.Network.search_all(conn, max_results=-1)
INFO:infoblox_client.connector:Sending get request to https://10.40.240.113/wapi/v1.4/network?_max_results=-1&_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs with parameters {'headers': {'Content-type': 'application/json'}, 'timeout': 10}
/usr/lib/python3.5/site-packages/requests-2.9.1-py3.5.egg/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
DEBUG:requests.packages.urllib3.connectionpool:"GET /wapi/v1.4/network?_max_results=-1&_return_fields=network_view%2Cnetwork%2Coptions%2Cmembers%2Cextattrs HTTP/1.1" 400 None
DEBUG:infoblox_client.connector:Error occured on object search: b'{ "Error": "AdmConProtoError: Result set too large (> 1)", \n  "code": "Client.Ibap.Proto", \n  "text": "Result set too large (> 1)", \n  "trace": "  File \\"ibapapachemod.py\\", line 355, in handlerequest\\n  File \\"wapibase.py\\", line 1428, in execute\\n  File \\"wapibase.py\\", line 1383, in _exec_handler\\n  File \\"wapihandler.py\\", line 604, in execute\\n  File \\"wapibaseobj.py\\", line 1452, in read\\n"\n}'
[]


So looks like behavior you are experiencing is caused by something else.
