### ISSUE TITLE
_return_fields limits lower border of wapi_version

### ISSUE THREAD

**Issue by bondar-pavel** [infobloxopen/infoblox-client#11]
On each request list of _return_fields is sent to NIOS.
But if field that is present in _return_fields is not supported by current wapi_version then request fails.
For example EADefinition return_fields requires wapi_version 2.2, on wapi_version below 2.2 any request to this object will fail.
Currently possible workaround for package users are:
- set return_fields manually on search, where each listed field exists for selected wapi version;
- set retuen_fields=[], so default fields for defined on NIOS for particular wapi version to be returned;

Need to discuss possible ways to fix it (failing on lower wapi_version) on infoblox_client side.

**Comment by yuewko** [comment]
Off the top of my head....

I believe we should explicitly specify the return_fields that we absolutely need. This will also tell us precisely the minimum wapi_version required. Then, we can simply validate the wapi_version at install time or start up time.

**Comment by yashkin** [comment]
Forcing user to specify ```return_fields``` to mitigate API versions gap, probably, is not a good way to do.
Also keep using the _same_ python class to represent object for all API versions will lead to overcomplicating and bloating of the implementation. Since with all new API versions object fields could be renamed or simply deleted.

So probably the better solution will include the separating of objects of each API version. And in this case we will never face the problem with inconsistency of available attributes in client objects with server one.

The same approach already used in openstack python clients such as ```neutron```, ```nova```, to name some of them. I believe that it is perfectly correct to borrow the concept of versioning.

**Comment by bondar-pavel** [comment]
I agree with @yashkin, looks like the most reliable way is to have set of objects for each api version.

**Comment by bondar-pavel** [comment]
Closing this one as stale issue
