### ISSUE TITLE
How to use fields not defined in objects.py

### ISSUE THREAD

**Issue by arnaudcoquelet** [infobloxopen/infoblox-client#110]
Is there a generic way to set/fetch a field that is not defined in _fields or _search_fields  ?

For instance, if I want to create a FixedAddress with `ignore_dhcp_option_list_request` set to **True**, the only way was to add that field to the `_fields` under  `class FixedAddressV4(FixedAddress):`

Is there a more generic way to do that ?

**Comment by bondar-pavel** [comment]
@arnaudcoquelet Currently to set/get some field for object it has to be defined in  ```_fields```. For now there is no other way except adding new fields to ```_fields```.

The goal is to have all fields defined in wapidoc for each object to be represented in ```_fields``` in infoblox-client. But adding all the fields for all the objects from wapidoc will take a while. Some fields have complex subfields, so they need some extra coding, rather than just adding field to _fields list.

So current approach is to add new fields as they become needed. Once you found field that is needed, please create issue here:
"Need field XXX for YYY object"
And I will work on adding it once I have some free cycles. alternatively you can create Pull Request with needed changes.

**Comment by johnbelamaric** [comment]
I believe that in recent versions there is a machine-readable schema available for WAPI, which may allow you to generate some of this automatically.

**Comment by bondar-pavel** [comment]
@johnbelamaric thanks! I will take a look at it.

**Comment by lingfish** [comment]
From https://community.infoblox.com/t5/Security/Is-there-a-WADL-available/td-p/541

> We do not have WADL available at this point, but as of NIOS 7.1 we do have a schema available.  
>  
> curl -k1 -u ibuser -X GET https://[gridmaster]/wapi/v2.1/?_schema
>  
> will give you the list of WAPI versions and objects supported with WAPI 2.1
>  
> To get the schema of an object, put the object in the URI - e.g., curl -k1 -u ibuser -X GET https://[gridmaster]/wapi/v2.1/record:host?_schema will give you the schema for the host record object

**Comment by sarya-infoblox** [comment]
Hi @arnaudcoquelet Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment]
Closing the issue as no response from the user.
