### ISSUE TITLE
cannot get options variable when i get a network .

### ISSUE THREAD

**Issue by fredgnucc** [infobloxopen/infoblox-client#264]
Hello Guys , 

i was creating my call by myself in the past to get/create infoblox data , 

iam starting using you python module which is doing more things ^^

when i try to use this method : all good 👍 

network = conn.get_object('network', {'network': args.network , 'network_view': network_view[0]['name']  })

[{'_ref': 'network/ZG5zLm5ldHdvcmskMTAuMjM3LjI0NS4wLzI2LzY4:10.237.245.0/26/32830', 'network': '10.237.245.0/26', 'network_view': '32830'}]

but when i look into the code of your NetworkV4 object  i see that you have set return_fields for only some key , 

if i want to get more key in the result what shoud i do? ( for example i want to see the options key related to the dhcp_options )

**Comment by JonasKs** [comment]
Which version of `infoblox_client` do you use? If it's not version `0.5.0` I'd highly suggest you update to the newest version. If you're using `pip` you can do it by issuing the following command: `pip install infoblox-client --upgrade` 

The new version (`0.5.0`) has all(I believe) return fields, so this should solve your problem. 

If that still don't work(try upgrading first!), you can extend the `NetworkV4` object yourself. This is untested code, but it should be something like this:

```py
class CustomNetworkV4(NetworkV4):
    _return_fields = ['ipv6addr', 'duid', 'network_view', 'extattrs', '<your-dhcp-field>']
```
You can then call on `CustomNetworkV4` instead of `NetworkV4`.

**Comment by fredgnucc** [comment]
Hey JonasKs

First thanks you for your fast reply 👍 

objects.NetworkV4.search ( conn , return_fields= ['options'], network_view= network_view[0]['name'] , cidr =  args.network  ) )

works like a charm :) i think i was missunderstanding some part of the library now all good .

thanks for the work done really nice library

NetworkV4: options="[Dhcpoption: name="dhcp-lease-time", num="51", use_option="False", value="43200", vendor_class="DHCP", Dhcpoption: name="routers", num="3", use_option="True", value="10.237.245.1", vendor_class="DHCP"]", _ref="network/ZG5zLm5ldHdvcmskMTAuMjM3LjI0NS4wLzI2LzY4:10.237.245.0/26/32830"

Cheers man

**Comment by JonasKs** [comment]
Good stuff 👍 

Please close the ticket :)

**Comment by fredgnucc** [comment]
all good guys !
