### ISSUE TITLE
zone_format has been removed from return_fields in DNSZone

### ISSUE THREAD

**Issue by gaetanpouilly** [infobloxopen/infoblox-client#355]
Hello,

According to this commit : https://github.com/infobloxopen/infoblox-client/commit/4d8b2a42d6064befd228af973e4dae0dcbfe7f16#diff-2cb2ff0980030546f9428ba747474917b82871b9fef68df20ee47fdf59758b44

At line 18130 from infoblox_client/objects.py file, the variable zone_format has been removed from _returns_fields
Is it possible to return it ?

Best Regards

**Comment by sarya-infoblox** [comment]
Hi @gaetanpouilly, Can you let me know why you need zone_format in _returns_fields? As this was removed based on the past requirements.

**Comment by gaetanpouilly** [comment]
Hi @sarya-infoblox, we used it to get forward zone.

**Comment by achernevskii** [comment]
@gaetanpouilly hello. 

We auto-generate `objects.py` file based on the WAPI schema, which one can fetch from the NIOS instance. 

WAPI field will be in the `_return_fields` list, if it's marked in schema as a `standard_field`. 

You can get `zone_format` field definition using curl:
```bash
curl -k1 -u ${WAPI_USER}:${WAPI_PASS} -X GET https://${WAPI_HOST}/wapi/v2.3/zone_auth\?_schema\&_schema_version\=2 | jq '.fields[] | select(.name=="zone_format")' 
```

As you can see in the result this field is not standard:
```json
{
  "enum_values": [
    "FORWARD",
    "IPV4",
    "IPV6"
  ],
  "is_array": false,
  "name": "zone_format",
  "searchable_by": "=",
  "standard_field": false,
  "supports": "rws",
  "type": [
    "enum"
  ]
}
```

I don't think that adding exception to the `objects.py` generation process is necessary, since a lib user have a lot of ways to modify `_return_fields` list, if they need different fields to be returned during get operations.

For example, if you're searching for a zone, you can specify `return_fields` as an argument to the `search` method like this:
```python
res = objects.DNSZone.search(                                                                                                                                                                                  
   conn,
   return_fields=['fqdn', 'view', 'zone_format'],
   view="default",                                                                                                                                                                             
) 
```
If you have some different use case, and you struggling with it, please let me know.

**Comment by sarya-infoblox** [comment]
Hi @gaetanpouilly Could you please confirm if the solution provided above worked for you?

**Comment by gaetanpouilly** [comment]
Hi,
It works for me , thx
