### ISSUE TITLE
in object_manager, add a new api: count_networks()

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#55]
Please add the following API:

def count_networks(self, network_view_name):
        ib_networks = ib_objects.Network.search_all(self.connector,
                                                                                network_view=network_view_name)
        return len(ib_networks)

This is used to determine the last subnet in the current network view which can be used in subnet removal.

**Comment by bondar-pavel** [comment]
I don't think we need to add method for that, since we grab all networks for network view and do not actually return them.
Most likely we would like to do something with networks if they are searched (for example delete/update),
so it is better to use ib_objects directly.
count_networks() would add the same inefficency level as network_exist had 52e82f20e1d6244d3d3ff98d92e4a61709d64b68, because if something should be done within already found networks, it has to be searched once again.

**Comment by hosunghwang** [comment]
I am actually using this case in line 342 from https://review.openstack.org/#/c/262633/3/networking_infoblox/neutron/common/ipam.py

ib_networks = ib_objects.Network.search_all(self.ib_cxt.connector,
                                            network_view=network_view)
is_last_subnet_in_netview = len(ib_networks) == 1

It would be nice if I don't have to count networks returned from search_all.
But this is good to have but not must-have.

**Comment by bondar-pavel** [comment]
I would say that using seach_all + len on client side is right way to count networks,
since otherwise we need to introduce pretty inefficient api calls as part of standart interface.
So I am trying to avoid it.
Will close it as wontfix for now, but we can come back to discussion if somebody strictly need it.
