### ISSUE TITLE
ssl_verify field in connector is not used correctly

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#83]
The following line has to be included in _parse_options().

          self.ssl_verify = utils.try_value_to_bool(self.ssl_verify, strict_mode=False)

so that other get/update/delete_object method can use the correct value since theose meothds
access self.ssl_verify directly.
 You can add it right before self.wapi_url line.

utils.try_value_to_bool() used in the _configure_session has no use.
You can just set it like this:
           self.session.verify = self.ssl_verify
since self.ssl_verify is already converted to True/False.

$ diff infoblox_client/connector.py /usr/local/lib/python2.7/dist-packages/infoblox_client/connector.py

          100a101,102
          >         self.ssl_verify = utils.try_value_to_bool(self.ssl_verify,
          >                                                   strict_mode=False)
          113,114c115
          <         self.session.verify = utils.try_value_to_bool(self.ssl_verify,
          <                                                       strict_mode=False)
          ---
          >         self.session.verify = self.ssl_verify

**Comment by bondar-pavel** [comment]
Actually there is no need to set 'verify flag for both session and request.
Since ssl_verify is configured on connector basis, then it would be enough to set it only for session,
and do not override it on request level.
I have tested solution where verify is set only for session and not changed for request, and it worked correctly.
Preparing fix.
